name: SportCenter CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Проверка Бэкенда
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Backend Deps
        run: |
          cd back
          pip install -r requirements.txt
          pip install flake8 pytest pytest-flask requests-mock

      - name: Lint Backend
        run: |
          cd back
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Backend Tests
        run: |
          cd back
          python -m pytest

      # Проверка Фронтенда (my-app)
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Frontend Deps
        run: |
          cd my-app
          npm install

      - name: Run Frontend Tests
        run: |
          cd my-app
          npm test
